# Change these first
owner: snigdhalinux # Your GitHub organization or username, where this repository lives
repo: snigdhaos-upptime # The name of this repository
assignees:
  - eshanized
  - snigdhalinux

sites:
  - name: BD-MIRROR
    url: https://bd-mirror.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: IN-MIRROR
    url: https://in-mirror.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: US-MIRROR
    url: https://us-mirror.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: UK-MIRROR
    url: https://uk-mirror.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: GE-MIRROR
    url: https://ge-mirror.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: RU-MIRROR
    url: https://ru-mirror.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: WW-MIRROR
    url: https://ww-mirror.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: AF-MIRROR
    url: https://af-mirror.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: JP-MIRROR
    url: https://bd-mirror.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: SNIGDHA-GLOBE
    url: https://snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: SNIGDHA-BUILD
    url: https://iso.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: SNIGDHA-FORUM
    url: https://forum.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: SNIGDHA-WIKI
    url: https://wiki.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  - name: SNIGDHA-STATUS
    url: https://snigdhalinux.github.io/snigdhaos-upptime/
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg

status-website:
  favicon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.png
  faviconSvg: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.svg
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /snigdhaos-upptime
  logoUrl: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-green.svg
  name: Snigdha OS Upptime
  introTitle: "Am I running?"
  introMessage: This is upptime monitoring page of Snigdha OS servers hosted on GitHub
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://snigdhaos.org/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
