# Change these first
owner: snigdhalinux # Your GitHub organization or username, where this repository lives
repo: snigdhaos-upptime # The name of this repository
assignees:
  - eshanized
  - snigdhalinux

sites:
  - name: SNIGDHA-GLOBE
    url: https://snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.svg
  - name: SNIGDHA-ARCTIC
    url: https://builds.snigdhaos.org/repo/arctic
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.svg
  - name: SNIGDHA-BADBLOOD
    url: https://builds.snigdhaos.org/repo/badblood
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.svg
  - name: SNIGDHA-WAREWOLF
    url: https://builds.snigdhaos.org/repo/warewolf
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.svg
  - name: SNIGDHA-FORUM
    url: https://forum.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.svg
  - name: SNIGDHA-WIKI
    url: https://forum.snigdhaos.org
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.svg
  - name: SNIGDHA-STATUS
    url: https://snigdhalinux.github.io/snigdhaos-upptime/
    icon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.svg

status-website:
  favicon: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.png
  faviconSvg: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.svg
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /snigdhaos-upptime
  logoUrl: https://raw.githubusercontent.com/snigdhalinux/snigdhaos-icon/master/usr/share/icons/snigdhaos/snigdhaos-purple.svg
  name: Snigdha OS Upptime
  introTitle: "Am I running?"
  introMessage: This is upptime monitoring page of Snigdha OS servers hosted on GitHub
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: https://snigdhaos.org/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
